name: Spotify Backup

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Python deps
        run: |
          pip install requests

      - name: Run spotify_backup.py
        run: |
          python spotify_backup.py

      - name: Commit
        run: |
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatic update"
          git push