name: Spotify Backup

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 * * * *'

jobs:
  spotify_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Python deps
        run: |
          pip install requests==2.25.0 pathvalidate==2.3.2

      - name: Run spotify_backup.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
        run: |
          python spotify_backup.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/*
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatic update"
          git push